### ISSUE TITLE
Relay access denied

### ISSUE THREAD

**Issue by ghost** [ak545/dns-domain-expiration-checker#11]
Hi, I have a 2 problems with the script.
1. *.eu domains don't work, script shows "Error" only or "Domains that caused errors".
2. script won't to send email to me with output. Telegram works fine. At the end of script I see this only:

{'my@mail.com': (454, b'4.7.1 <my@mail.com>: Relay access denied')}

SMTP address is correct. Tried port 25, 587, 465.

I'm using:
python3 /home/myusername/domains/ddec.py -f /home/myusername/domains/domains.txt -c -i 5 -x 30 -t -e my@mail.com

Any help please?
Thank you.

**Comment by ak545** [comment]
> Hi, I have a 2 problems with the script.
> 
> 1. *.eu domains don't work, script shows "Error" only or "Domains that caused errors".

Sorry, but ***.eu** domains not supported because EU Registrant say "**NOT DISCLOSED! Visit www.eurid.eu for webbased WHOIS.**". Probably the privacy policy of the European Union. I won't argue with him. No so no. What sacred meaning is laid in this secrecy, I do not understand.
In the new version 0.2.15, I just added the .eu domain to the unsupported list so that the script didn't crash.



> 2. script won't to send email to me with output. Telegram works fine. At the end of script I see this only:
> 
> {'[my@mail.com](mailto:my@mail.com)': (454, b'4.7.1 [my@mail.com](mailto:my@mail.com): Relay access denied')}
> 
> SMTP address is correct. Tried port 25, 587, 465.
> 
> I'm using: python3 /home/myusername/domains/ddec.py -f /home/myusername/domains/domains.txt -c -i 5 -x 30 -t -e [my@mail.com](mailto:my@mail.com)
> 
Usually like this:
If the mail server uses port 465 to send emails, it means it uses SSL encryption (try adding the **-ssl** option).

If the mail server uses port 587 to send emails, it means that it uses STARTTLS encryption (try adding the **-starttls** option)

It's also a good idea to try the **-auth** option, as usually mail servers don't allow you to send emails to just anyone. In this case, in the body of the script itself, the **SMTP_SENDER** and **SMTP_PASSWORD** variables must additionally be updated.

One last thing: it's still better to use the **-ee** option as well

And in the end:

`python3 /home/myusername/domains/ddec.py -f /home/myusername/domains/domains.txt -ee -c -i 5 -x 30 -t -ssl -auth -e my@mail.com`

or

`python3 /home/myusername/domains/ddec.py -f /home/myusername/domains/domains.txt -ee -c -i 5 -x 30 -t -starttls -auth -e my@mail.com`


> Any help please? Thank you.
