### ISSUE TITLE
Error on .nz domains

### ISSUE THREAD

**Issue by drak42** [ak545/dns-domain-expiration-checker#2]
Hi,

Is it possible to add support for the following domains?
.co.nz
.nz
.blog
.com.au

We use Freeparking as our registrar for a lot of our domains, that does not seem to be supported well, any chance that can be looked at to?

Thanks

**Comment by ak545** [comment]
Hello!

Unfortunately, **.co.nz**, **.nz** and **.com.au** are not supported due to force majeure restrictions on the part of the owners of these domains. Owners of these domains do not provide any useful whois-information in responses to whois-requests.
The only way to find out the necessary information is to read the raw answer to the whois-request, and if there is any link like this https://www.dnc.org.nz/whois/search?domain_name=stuff.co.nz
analyze the response after breaking the barrier from reCAPTCHA. But since this is not a standard situation, and the content of answers to whois-requests can be arbitrary, I will not do such an analysis. In addition, the owners of these domains do not welcome such actions.

> **Terms of Use**: By submitting a WHOIS query you are entering into an agreement with Domain Name Commission Ltd on the following terms and conditions, and subject to all relevant .nz Policies and procedures as found at https://dnc.org.nz/. It is prohibited to:
> - Send high volume WHOIS queries with the effect of downloading part of or all of the .nz Register or collecting register data or records;
> - Access the .nz Register in bulk through the WHOIS service (ie. where a user is able to access WHOIS data other than by sending individual queries to the database);
> - Use WHOIS data to allow, enable, or otherwise support mass unsolicited commercial advertising, or mass solicitations to registrants or to undertake market research via direct mail, electronic mail, SMS, telephone or any other medium;
> - Use WHOIS data in contravention of any applicable data and privacy laws, including the Unsolicited Electronic Messages Act 2007;
> - Store or compile WHOIS data to build up a secondary register of information;
> - Publish historical or non-current versions of WHOIS data; and
> - Publish any WHOIS data in bulk.
> 
> Copyright Domain Name Commission Limited (a company wholly-owned by Internet New Zealand Incorporated) which may enforce its rights against any person or entity that undertakes any prohibited activity without its written permission. The WHOIS service is provided by NZRS Limited.


I did not find any problems with the **.blog** domain. Here is an example parsing my.blog domain:

`my.blog whois.centralnic.com Knock Knock WHOIS There, LLC 10/19/2020 Valid (165)`

![2020-05-08_01-09-52](https://user-images.githubusercontent.com/12557874/81349507-c4553980-90c8-11ea-924d-a43cdf834cfd.png)

**Comment by drak42** [comment]
Thanks for that feedback, really appreciate your time
